# Generated by Django 2.2.2 on 2019-07-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20190711_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='m_no',
            field=models.CharField(max_length=12),
        ),
    ]
