# Generated by Django 2.2.2 on 2019-07-12 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_category_color_design_product_productimage_salesorder_salesorderdetail_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='color_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Color'),
        ),
        migrations.AlterField(
            model_name='product',
            name='design_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Design'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Product'),
        ),
        migrations.AlterField(
            model_name='salesorder',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.User'),
        ),
        migrations.AlterField(
            model_name='salesorderdetail',
            name='sales_order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.SalesOrder'),
        ),
    ]
