# Generated by Django 2.2.2 on 2019-07-12 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_product_supplier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salesorderdetail',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Product'),
        ),
    ]
