# Generated by Django 2.2.2 on 2019-07-18 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190712_1918'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
