# Generated by Django 2.2.2 on 2019-07-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_cart_cartdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='date_placed',
        ),
        migrations.AddField(
            model_name='cartdetail',
            name='date_add',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
